[features]
seeds = false
skip-lint = false

[programs.localnet]
constants = "E146Yz6pKA6USTSqzHZss27vs7jXoBVU6agdXXU97JQC"

[programs.devnet]
quantcoin_presale = "E146Yz6pKA6USTSqzHZss27vs7jXoBVU6agdXXU97JQC"

[registry]
url = "https://api.anchor-api.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
